In [1]:
import numpy as np

In [2]:
grid = np.array(
    [[5, 3, 0, 0, 7, 0, 0, 0, 0],
     [6, 0, 0, 1, 9, 9, 0, 0, 0],
     [0, 9, 8, 0, 0, 0, 0, 6, 0],
     [8, 0, 0, 0, 6, 0, 0, 0, 3],
     [4, 0, 0, 8, 0, 3, 0, 0, 1],
     [7, 0, 0, 0, 2, 0, 0, 0, 6],
     [0, 6, 0, 0, 0, 0, 2, 3, 0],
     [0, 0, 0, 4, 1, 9, 0, 0, 5],
     [0, 0, 0, 0, 8, 0, 0, 7, 9]]
)
print(grid)

[[5 3 0 0 7 0 0 0 0]
 [6 0 0 1 9 9 0 0 0]
 [0 9 8 0 0 0 0 6 0]
 [8 0 0 0 6 0 0 0 3]
 [4 0 0 8 0 3 0 0 1]
 [7 0 0 0 2 0 0 0 6]
 [0 6 0 0 0 0 2 3 0]
 [0 0 0 4 1 9 0 0 5]
 [0 0 0 0 8 0 0 7 9]]


![convert notebook to web app](https://www.researchgate.net/profile/Paul-Roach-4/publication/264572573/figure/fig1/AS:295976259604480@1447577647208/An-Example-Sudoku-Puzzle-and-its-Solution-1.png)

In [3]:
def possible(row, col, num):
    global grid
    # Check if number is in row
    for n in range(9):
        if grid[row][n] == num:
            return False
    # Check if number is in col
    for n in range(9):
        if grid[n][col] == num:
            return False
    # Check if number is in 3x3 box
    row_offset = (row // 3) * 3
    col_offset = (col // 3) * 3
    for i in range(3):
        for j in range(3):
            if grid[row_offset+i][col_offset+j] == num:
                return False
    return True

In [4]:
def check(grid):
    nums = {0, 1, 2, 3, 4, 5, 6, 7, 8}
    for x in range(9):
        # Rows Check
        if nums != set(grid[x, :]):
            return False
        # Columns Check
        if nums != set(grid[:, x]):
            return False
    
    # Boxes Check
    for x in [0, 3, 6]:
        for y in [0, 3, 6]:
            if nums != set(grid[x:x+3, y:y+3].flatten()):
                return False
    return True

In [5]:
def solve():
    global grid
    for i in range(9):
        for j in range(9):
            if grid[i][j] == 0:                    
                for n in range(1,10):
                    if possible(i, j, n):
                        grid[i][j] = n
                        solve()
                        grid[i][j] = 0
                return
    print(grid)
    input("More?")

In [6]:
solve()

[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 3 5 0 1 6 2]
 [8 1 2 5 6 7 4 0 3]
 [4 5 6 8 0 3 7 2 1]
 [7 0 3 9 2 1 5 8 6]
 [1 6 5 7 0 0 2 3 4]
 [2 7 0 4 1 9 6 0 5]
 [3 4 0 6 8 2 0 7 9]]
[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 3 5 0 1 6 2]
 [8 1 2 5 6 7 4 0 3]
 [4 5 6 8 0 3 7 2 1]
 [7 0 3 9 2 1 5 8 6]
 [1 6 5 7 0 0 2 3 4]
 [2 7 0 4 1 9 6 0 5]
 [3 4 0 6 8 5 0 7 9]]
[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 3 5 0 1 6 2]
 [8 1 2 5 6 7 4 0 3]
 [4 5 6 8 0 3 7 2 1]
 [7 0 3 9 2 1 5 8 6]
 [1 6 5 7 0 0 2 3 4]
 [2 7 0 4 1 9 6 0 5]
 [3 4 0 6 8 5 0 7 9]]
[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 3 5 0 1 6 2]
 [8 1 2 5 6 7 4 0 3]
 [4 5 6 8 0 3 7 2 1]
 [7 0 3 9 2 1 5 8 6]
 [1 6 5 7 0 0 2 3 4]
 [2 7 0 4 1 9 6 0 5]
 [3 4 0 6 8 5 0 7 9]]
[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 3 5 0 1 6 2]
 [8 1 2 5 6 7 4 0 3]
 [4 5 6 8 0 3 7 2 1]
 [7 0 3 9 2 1 5 8 6]
 [1 6 5 7 0 0 2 3 4]
 [2 7 0 4 1 9 6 0 5]
 [3 4 0 6 8 5 0 7 9]]
[[5 3 1 2 7 4 8 9 0]
 [6 2 4 1 9 9 3 5 7]
 [0 9 8 

In [7]:
grid

array([[5, 3, 1, 2, 7, 6, 8, 9, 0],
       [6, 2, 4, 1, 9, 9, 3, 5, 7],
       [0, 9, 8, 3, 5, 0, 1, 6, 4],
       [8, 1, 2, 5, 6, 7, 4, 0, 3],
       [4, 5, 6, 8, 0, 3, 9, 2, 1],
       [7, 0, 3, 9, 2, 1, 5, 8, 6],
       [1, 6, 9, 7, 0, 0, 2, 3, 8],
       [2, 8, 7, 4, 1, 9, 6, 0, 5],
       [3, 4, 0, 6, 8, 5, 0, 7, 9]])

In [8]:
check(grid)

False